- name: Set variables
  set_fact:
    consul_http_addr: "http://127.0.0.1:8500"
    vault_http_addr: "http://127.0.0.1:8200"
    consul_master_token: "master"
    vault_master_token: "master"

- name: acl bootstrap nomad
  shell:
    cmd: (./nomad acl bootstrap > bootstrap.token) && awk '/Secret/ {print $4}' bootstrap.token
  register: secret_id

- name: print accessor ID
  shell:
    cmd: awk '/Accessor/ {print $4}' bootstrap.token
  register: accessor_id

- name: add bootstrap token to vault
  shell:
    cmd: ./vault kv put secret/nomad-bootstrap-token accessor-id="{{ accessor_id.stdout }}" secret-id="{{ secret_id.stdout }}"
  environment:
    VAULT_ADDR: "{{ vault_http_addr.stdout }}"
    ./vault kv put secret/nomad-bootstrap-token accessor-id="e927868b-6a4e-dbd5-2f31-5bb5b32937b9" secret-id="1bdd7e7a-6eb6-bd35-b915-4661ae0e802b"

- name: delete bootstrap.token file
  file:
    path: bootstrap.token
    state: absent

- name: create default policy write
  shell:
#    cmd: nomad acl policy apply -token {{ secret_id.stdout }} -description "Default write policy" write-default /etc/nomad.d/policies/write_policy.hcl
    cmd: ./nomad acl policy apply -token {{ secret_id.stdout }} -description "Default write policy" write-default cluster/ansible/nomad-policies/write_policy.hcl

- name: create default policy read
  shell:
#    cmd: nomad acl policy apply -token {{ secret_id.stdout }} -description "Default read policy" read-default /etc/nomad.d/policies/read_policy.hcl
    cmd: nomad acl policy apply -token {{ secret_id.stdout }} -description "Default read policy" read-default cluster/ansible/nomad-policies/read_policy.hcl

#- name: Add a fact file - nomad_acl.fact
#  blockinfile:
#    path:  /etc/ansible/facts.d/nomad_acl.fact
#    block: |
#      [bootstrap]
#      completed=true
#    create: yes
